### ISSUE TITLE
Error 1071: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by thehowl** [lafriks/xormstore#5]
Hey, of course this is related to Gitea, specifically issue https://github.com/go-gitea/gitea/issues/3859 . It would seem that creating the table picks by default the global charset of the mysql database - can you please make it so that it creates it with the utf8 charset and not utf8mb4? So that there is no need for manual user intervention when they need to upgrade gitea. (I had this issue on my server myself today - and I'm still trying to find a fix, for that matter :sweat_smile: )

**Comment by lafriks** [comment]
I have to check if I can set xorm such option. Currently it comes from Gitea when creating connection to set that. (There is PR for gitea to set that I think)

**Comment by silverwind** [comment]
As mentioned in the other issue, I think a `VARCHAR(400)` in `utf8` will bust the size limit of 767 bytes as it uses 3 bytes per character. Suggestion would be to either cut down it's size to `VARCHAR(191)` or store it as `latin1` or other 1-bytes encodings.
